### ISSUE TITLE
How to normalize CNA and RNA data before NMF? What is the normalization method in the example data

### ISSUE THREAD

**Issue by SepOrion** [broadinstitute/PANOPLY#29]
"Both CNA (normalized log-ratio, derived from WXS, WGS or combination) and RNA expression (log-transformed and normalized, derived from RNAseq) data are required. These data must be normalized prior to input in PANOPLY.“

What is the data type before normalization of RNA and CNA, and what is the normalizaition performed before NMF？What is the normalization method in the example data？

For example, the RNA data before normalization is FPKM or TPM? Then  perform log2 normalization on RNA data？

**Comment by drmani** [comment]
The input data in the tutorial are as follows:
* RNA data was quantified using RSEM4 and normalized within samples to a fixed upper quartile. The data were then log2 transformed. Further, each gene was median centered.
* CNA data were obtained from the SNP chip, followed by normalization (division by 2) and log2 transformation.

The NMF clustering module takes data on a similar scale as proteomics data (ie log ratios to a feature-relative reference), and z-scores are calculated across samples (columns) before performing NMF clustering. See https://github.com/broadinstitute/PANOPLY/wiki/Data-Analysis-Modules%3A-panoply_mo_nmf.
