### ISSUE TITLE
Alphabet function

### ISSUE THREAD

**Issue by hsiaoyi0504** [broadinstitute/PANOPLY#30]
Hi there, the question is not directly related to any bug, but I can't find any place in which this
`alphabet` function is defined. This `alphabet` function seems to generate a whole series of alphabets, though.

https://github.com/broadinstitute/PANOPLY/blob/39133217c4c60d2e71e790d2fa253040d03fa62b/src/panoply_mo_nmf/nmf_functions.R?_pjax=%23repo-content-pjax-container#L1057

**Comment by karstenkrug** [comment]
Hi, the <code>alphabet</code> function is part of the <code>pals</code> R package: 

https://cran.r-project.org/web/packages/pals/vignettes/pals_examples.html

**Comment by hsiaoyi0504** [comment]
Got it. Thanks!
