### ISSUE TITLE
The source R files in R-utiliites

### ISSUE THREAD

**Issue by wangshisheng** [broadinstitute/PANOPLY#34]
Hi all,

Where could I find the source r files in the R-utiliites? For example,

Rutil.path <- switch (Sys.info()[['sysname']],
                      Windows = {'//flynn-cifs/prot_proteomics/Projects/R-utilities'},
                      Darwin = {'/Volumes/prot_proteomics/Projects/R-utilities'},
                      Linux = {'/prot/proteomics/Projects/R-utilities'})

I use Windows and I can not find where is the path '//flynn-cifs/prot_proteomics/Projects/R-utilities'.

Could someone share these r files in this path? Thanks a lot really.

Shisheng

**Comment by drmani** [comment]
The dockers for each PANOPLY task contain the required code in the Linux path (/prot/proteomics/Projects/R-utilities). The Windows and MacOS (Darwin) paths are internal to the Broad Institute.

**Comment by wangshisheng** [comment]
Thanks a lot, I will try it~~

**Comment by wangshisheng** [comment]
> The dockers for each PANOPLY task contain the required code in the Linux path (/prot/proteomics/Projects/R-utilities). The Windows and MacOS (Darwin) paths are internal to the Broad Institute.

Hi drmani,

I have installed docker and do not know how to run the dockers. There is no introduction either. Could you give one example about how to run the docker in PANOPLY?
Thanks a lot~~

Bests.

**Comment by drmani** [comment]
A docker tutorial is beyond the scope of PANOPLY -- google is your best bet for instructions. 

But, if you want to run a docker (say broadcptac/panoply_common:1_1) and inspect the R-utilities code, you can run:
% docker run -ti broadcptac/panoply_common:1_1 /bin/bash
This will put you in the docker, with a shell prompt and you can explore the files in the docker.
