### ISSUE TITLE
Initialization cell in PANOPLY-startup-notebook never finishes

### ISSUE THREAD

**Issue by wnojopra** [broadinstitute/PANOPLY#35]
Hi, 

Thanks for creating these workspaces in Terra. They've been a great resource. 

I'm following the [tutorial](https://github.com/broadinstitute/PANOPLY/wiki/PANOPLY-Tutorial) and I and a few others teammates are getting stuck initializing the notebook. After cloning the workspace and starting a cloud environment with the `broadcptac/panda:1_0` container image, I try to run the first cell  in the PANOPLY-startup-notebook. This cell seems to hang and never finish, even after waiting for several hours. 

A teammate opened up the terminal this afternoon and it looks like it's in an endless loop, presumably because the `broadcptac/panda:1_0` image is missing a package, and thus it's never able to load:

![image](https://user-images.githubusercontent.com/6879774/170156294-25f09b80-36cf-44d3-8cb6-e87f45c6c324.png)
Any suggestions for how we can move past this step? Thanks!

**Comment by drmani** [comment]
The docker takes too long to download, and hence the compute environment does not initialize properly. We have fixed the issue, and we are in the process of updating documentation. Please use `gcr.io/broadcptac/panda:1_2` as the docker. This is an updated docker stored on GCR, and should work more reliably.

**Comment by wnojopra** [comment]
Thank you @drmani ! After updating the docker image version I was able to succesfully run the initialize code. I'm looking forward to the documentation update but in the meantime I'll try and spread the word to my team.
