### ISSUE TITLE
(Document update) panoply_cna_setup and panoply_cna_correlation

### ISSUE THREAD

**Issue by hsiaoyi0504** [broadinstitute/PANOPLY#36]
It seems to me that the [document](https://github.com/broadinstitute/PANOPLY/wiki/Support-Modules%3A-panoply_cna_setup) of `panoply_cna_setup` module doesn't mention `subgroups.txt` is generated.

Also, relatively minor.  In the [document](https://github.com/broadinstitute/PANOPLY/wiki/Data-Analysis-Modules%3A-panoply_cna_correlation) of `panoply_cna_correlation`, it doesn't mention these two files but looks like it's required in the process (run-pipeline.sh, around 603 to 607 lines).

``` bash
groups=`cat subgroups.txt`
g=($groups)
# iterate through groups and execute cna-analysis.r for each
for i in `seq 1 "${#g[@]}"`; do
 line_i=`sed -n "${i}p" file_table.tsv`
```

Hope this helps other developers. Thanks.

**Comment by drmani** [comment]
Thanks for catching this. The `panoply_cna_correlation` should always be run using the tar file output from `panoply_cna_setup` as its input. In such a set up, the `subgroups.txt` and `file_table.tsv` files are internal to the workflow. We will update the documentation to reflect this.
