### ISSUE TITLE
Following tutorial with V1.3, run_panda() does not populate data

### ISSUE THREAD

**Issue by sooheon** [broadinstitute/PANOPLY#42]
Followed tutorial at https://github.com/broadinstitute/PANOPLY/wiki/PANOPLY-Tutorial step by step, the only change being to use [PANOPLY_Production_Pipelines_v1_3](https://app.terra.bio/#workspaces/broad-firecloud-cptac/PANOPLY_Production_Pipelines_v1_3) workspace and `broadcptac/panda:1_3` as the VM image. At the end of the run, the Data tab looks like the following, only `sample_set` table generated, and no data populated.

<img width="1747" alt="image" src="https://github.com/broadinstitute/PANOPLY/assets/302945/2c1ba6ae-1182-423f-b5ea-1bb3feac9b65">

It does not take a few hours, as the tutorial notes, but finishes within a minute or two.

**Comment by wcorinne** [comment]
The PANOPLY v1_4 release— which has now been made public— contains a number of Startup-Notebook patches. If the same issue still occurs in a v1_4 workspace, we can troubleshoot further with the logfile, which can be accessed from the terminal:
![image](https://github.com/broadinstitute/PANOPLY/assets/92993135/014a9e13-93bc-43ad-8736-dcf5822fb32a)
The logfile can be copied from the notebook VM to the workspace Data File folder with the following command:
`gsutil cp $WORKSPACE_NAME/edit/runspace/logfile_mn.txt $WORKSPACE_BUCKET`
<img width="1169" alt="image" src="https://github.com/broadinstitute/PANOPLY/assets/92993135/084f666e-de1c-4afc-ac44-52e087afb0b0">
<img width="1792" alt="image" src="https://github.com/broadinstitute/PANOPLY/assets/92993135/ac1e7400-3493-4e46-8297-e7b225d1cbf9">

Also, the shorter runtime of `run_panda()` is normal and should only take 5-10 minutes to complete successfully. The function was heavily re-optimized after v1_2, cutting the runtime from a few hours to a few minutes-- but the tutorial documentation still reflects v1_0.

**Comment by sooheon** [comment]
I've now tried with published V1_4, and `sample_set` is populated (though not multiple tables as indicated in tutorial, I assume this is due to version difference?)

However, moving on to the workflow, all 5 tasks in `panoply_main` failed.

<details>
<summary>workflow level failures</summary>
<img width="1148" alt="image" src="https://github.com/broadinstitute/PANOPLY/assets/302945/603e8c8d-dedf-4fd6-94c8-69e5807771e0">
</details>

Execution log: 
[workflow.151a5dfa-f5b2-478a-bf0f-be053843e850.log](https://github.com/broadinstitute/PANOPLY/files/14736081/workflow.151a5dfa-f5b2-478a-bf0f-be053843e850.log)


<details>

<summary>panoply_rna_protein_correlation.log:</summary>

```
2024/03/22 16:03:10 Starting container setup.
2024/03/22 16:03:11 Done container setup.
2024/03/22 16:03:13 Starting localization.
2024/03/22 16:03:26 Localization script execution started...
2024/03/22 16:03:26 Localizing input gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/submissions/9bae57da-2431-4314-89ca-64714a8070e2/panoply_main/151a5dfa-f5b2-478a-bf0f-be053843e850/call-panoply_rna_protein_correlation/script -> /cromwell_root/script
2024/03/22 16:03:30 Localizing input gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/master-parameters_tutorial.yaml -> /cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/master-parameters_tutorial.yaml
2024/03/22 16:03:31 Localizing input gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/rna-subset.gct -> /cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/rna-subset.gct
2024/03/22 16:03:31 Localizing input gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/proteome-subset.gct -> /cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/proteome-subset.gct
Copying gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/rna-subset.gct to file:///cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/rna-subset.gct
Copying gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/proteome-subset.gct to file:///cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/proteome-subset.gct
  
..

Average throughput: 135.1MiB/s
2024/03/22 16:03:33 Localization script execution complete.
2024/03/22 16:03:39 Done localization.
2024/03/22 16:03:40 Running user action: docker run -v /mnt/local-disk:/cromwell_root --entrypoint=/bin/bash broadcptac/panoply_rna_protein_correlation@sha256:8db7abb9fd4a43be0c233e885e7b9a38b2cdab5390426a543a03e0b120ce4a14 /cromwell_root/script
NULL
NULL
Error in source("config.r") : config.r:300:1: unexpected '}'
299:   min.numratio <- 
300: }
     ^
Execution halted
2024/03/22 16:03:43 Starting delocalization.
2024/03/22 16:03:43 Delocalization script execution started...
2024/03/22 16:03:43 Delocalizing output /cromwell_root/memory_retry_rc -> gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/submissions/9bae57da-2431-4314-89ca-64714a8070e2/panoply_main/151a5dfa-f5b2-478a-bf0f-be053843e850/call-panoply_rna_protein_correlation/memory_retry_rc
2024/03/22 16:03:46 Delocalizing output /cromwell_root/rc -> gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/submissions/9bae57da-2431-4314-89ca-64714a8070e2/panoply_main/151a5dfa-f5b2-478a-bf0f-be053843e850/call-panoply_rna_protein_correlation/rc
2024/03/22 16:03:47 Delocalizing output /cromwell_root/stdout -> gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/submissions/9bae57da-2431-4314-89ca-64714a8070e2/panoply_main/151a5dfa-f5b2-478a-bf0f-be053843e850/call-panoply_rna_protein_correlation/stdout
2024/03/22 16:03:49 Delocalizing output /cromwell_root/stderr -> gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/submissions/9bae57da-2431-4314-89ca-64714a8070e2/panoply_main/151a5dfa-f5b2-478a-bf0f-be053843e850/call-panoply_rna_protein_correlation/stderr
2024/03/22 16:03:50 Delocalizing output /cromwell_root/panoply_rna_protein_correlation-output.tar -> gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/submissions/9bae57da-2431-4314-89ca-64714a8070e2/panoply_main/151a5dfa-f5b2-478a-bf0f-be053843e850/call-panoply_rna_protein_correlation/panoply_rna_protein_correlation-output.tar
Required file output '/cromwell_root/panoply_rna_protein_correlation-output.tar' does not exist.
```

</details>

<details>
<summary>
subsea_rna.log
</summary>
2024/03/22 16:02:42 Starting container setup.
2024/03/22 16:02:43 Done container setup.
2024/03/22 16:02:44 Starting localization.
2024/03/22 16:02:52 Localization script execution started...
2024/03/22 16:02:52 Localizing input gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/submissions/9bae57da-2431-4314-89ca-64714a8070e2/panoply_main/151a5dfa-f5b2-478a-bf0f-be053843e850/call-ssgsea_rna/script -> /cromwell_root/script
2024/03/22 16:02:55 Localizing input gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/rna-subset.gct -> /cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/rna-subset.gct
2024/03/22 16:02:56 Localizing input gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/master-parameters_tutorial.yaml -> /cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/master-parameters_tutorial.yaml
2024/03/22 16:02:56 Localizing input gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/msigdb_v7.0_h.all.v7.0.symbols.gmt -> /cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/msigdb_v7.0_h.all.v7.0.symbols.gmt
Copying gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/master-parameters_tutorial.yaml to file:///cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/master-parameters_tutorial.yaml
Copying gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/msigdb_v7.0_h.all.v7.0.symbols.gmt to file:///cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/msigdb_v7.0_h.all.v7.0.symbols.gmt
  


Average throughput: 9.8MiB/s
2024/03/22 16:02:58 Localization script execution complete.
2024/03/22 16:03:02 Done localization.
2024/03/22 16:03:03 Running user action: docker run -v /mnt/local-disk:/cromwell_root --entrypoint=/bin/bash broadcptac/panoply_ssgsea@sha256:5bdb529bb513f986dd0786ade226e13a2e71b65b06abffd583803851861448f9 /cromwell_root/script


parsing command line parameters:
------------------------------------------------------------
--- gct_str /cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/rna-subset.gct ; prefer yaml? FALSE 
--- level gc ; prefer yaml? FALSE 
--- id_type NA ; prefer yaml? TRUE 
--- id_type_out NA ; prefer yaml? TRUE 
--- acc_type_in NA ; prefer yaml? TRUE 
--- seqwin_column NA ; prefer yaml? TRUE 
--- gene_symbol_column NA ; prefer yaml? TRUE 
--- humanize_gene_names NA ; prefer yaml? TRUE 
--- sgt_column NA ; prefer yaml? TRUE 
--- localized NA ; prefer yaml? TRUE 
--- mode NA ; prefer yaml? TRUE 
--- residue NA ; prefer yaml? TRUE 
--- ptm NA ; prefer yaml? TRUE 
--- preprocess_gct NA ; prefer yaml? TRUE 
--- libdir /home/pgdac/src ; prefer yaml? FALSE 
--- yaml_file /cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/master-parameters_tutorial.yaml ; prefer yaml? FALSE 
--- help FALSE ; prefer yaml? FALSE 


Updating parameter file with command line parameters:
------------------------------------------------------------
level : gc -> gc 
------------------------------------------------------------ 

importing gct file:  /cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/rna-subset.gct  ...
parsing as GCT v1.3
/cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/rna-subset.gct 15800 rows, 77 cols, 1 row descriptors, 13 col descriptors
Error in if (humanize.gene.names) genes <- toupper(genes) : 
  argument is not interpretable as logical
Calls: preprocessGCT
Execution halted
2024/03/22 16:03:13 Starting delocalization.
2024/03/22 16:03:14 Delocalization script execution started...
2024/03/22 16:03:14 Delocalizing output /cromwell_root/memory_retry_rc -> gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/submissions/9bae57da-2431-4314-89ca-64714a8070e2/panoply_main/151a5dfa-f5b2-478a-bf0f-be053843e850/call-ssgsea_rna/memory_retry_rc
2024/03/22 16:03:16 Delocalizing output /cromwell_root/rc -> gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/submissions/9bae57da-2431-4314-89ca-64714a8070e2/panoply_main/151a5dfa-f5b2-478a-bf0f-be053843e850/call-ssgsea_rna/rc
2024/03/22 16:03:18 Delocalizing output /cromwell_root/stdout -> gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/submissions/9bae57da-2431-4314-89ca-64714a8070e2/panoply_main/151a5dfa-f5b2-478a-bf0f-be053843e850/call-ssgsea_rna/stdout
2024/03/22 16:03:19 Delocalizing output /cromwell_root/stderr -> gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/submissions/9bae57da-2431-4314-89ca-64714a8070e2/panoply_main/151a5dfa-f5b2-478a-bf0f-be053843e850/call-ssgsea_rna/stderr
2024/03/22 16:03:21 Delocalizing output /cromwell_root/tutorial-proteome.tar.gz -> gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/submissions/9bae57da-2431-4314-89ca-64714a8070e2/panoply_main/151a5dfa-f5b2-478a-bf0f-be053843e850/call-ssgsea_rna/tutorial-proteome.tar.gz
Required file output '/cromwell_root/tutorial-proteome.tar.gz' does not exist.
</details>


<details>
<summary>
ssgsea_ome.log
</summary>
2024/03/22 16:04:42 Starting container setup.
2024/03/22 16:04:45 Done container setup.
2024/03/22 16:04:48 Starting localization.
2024/03/22 16:05:08 Localization script execution started...
2024/03/22 16:05:08 Localizing input gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/submissions/9bae57da-2431-4314-89ca-64714a8070e2/panoply_main/151a5dfa-f5b2-478a-bf0f-be053843e850/call-ssgsea_ome/script -> /cromwell_root/script
2024/03/22 16:05:14 Localizing input gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/proteome-subset.gct -> /cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/proteome-subset.gct
2024/03/22 16:05:18 Localizing input gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/master-parameters_tutorial.yaml -> /cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/master-parameters_tutorial.yaml
2024/03/22 16:05:18 Localizing input gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/msigdb_v7.0_h.all.v7.0.symbols.gmt -> /cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/msigdb_v7.0_h.all.v7.0.symbols.gmt
Copying gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/master-parameters_tutorial.yaml to file:///cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/master-parameters_tutorial.yaml
Copying gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/msigdb_v7.0_h.all.v7.0.symbols.gmt to file:///cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/msigdb_v7.0_h.all.v7.0.symbols.gmt
  
.

Average throughput: 1.0MiB/s
2024/03/22 16:05:21 Localization script execution complete.
2024/03/22 16:05:31 Done localization.
2024/03/22 16:05:32 Running user action: docker run -v /mnt/local-disk:/cromwell_root --entrypoint=/bin/bash broadcptac/panoply_ssgsea@sha256:5bdb529bb513f986dd0786ade226e13a2e71b65b06abffd583803851861448f9 /cromwell_root/script


parsing command line parameters:
------------------------------------------------------------
--- gct_str /cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/proteome-subset.gct ; prefer yaml? FALSE 
--- level gc ; prefer yaml? FALSE 
--- id_type NA ; prefer yaml? TRUE 
--- id_type_out NA ; prefer yaml? TRUE 
--- acc_type_in NA ; prefer yaml? TRUE 
--- seqwin_column NA ; prefer yaml? TRUE 
--- gene_symbol_column NA ; prefer yaml? TRUE 
--- humanize_gene_names NA ; prefer yaml? TRUE 
--- sgt_column NA ; prefer yaml? TRUE 
--- localized NA ; prefer yaml? TRUE 
--- mode NA ; prefer yaml? TRUE 
--- residue NA ; prefer yaml? TRUE 
--- ptm NA ; prefer yaml? TRUE 
--- preprocess_gct NA ; prefer yaml? TRUE 
--- libdir /home/pgdac/src ; prefer yaml? FALSE 
--- yaml_file /cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/master-parameters_tutorial.yaml ; prefer yaml? FALSE 
--- help FALSE ; prefer yaml? FALSE 


Updating parameter file with command line parameters:
------------------------------------------------------------
level : gc -> gc 
------------------------------------------------------------ 

importing gct file:  /cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/proteome-subset.gct  ...
parsing as GCT v1.3
/cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/proteome-subset.gct 10569 rows, 77 cols, 15 row descriptors, 17 col descriptors
Error in if (humanize.gene.names) genes <- toupper(genes) : 
  argument is not interpretable as logical
Calls: preprocessGCT
Execution halted
2024/03/22 16:05:51 Starting delocalization.
2024/03/22 16:05:52 Delocalization script execution started...
2024/03/22 16:05:52 Delocalizing output /cromwell_root/memory_retry_rc -> gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/submissions/9bae57da-2431-4314-89ca-64714a8070e2/panoply_main/151a5dfa-f5b2-478a-bf0f-be053843e850/call-ssgsea_ome/memory_retry_rc
2024/03/22 16:05:58 Delocalizing output /cromwell_root/rc -> gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/submissions/9bae57da-2431-4314-89ca-64714a8070e2/panoply_main/151a5dfa-f5b2-478a-bf0f-be053843e850/call-ssgsea_ome/rc
2024/03/22 16:06:01 Delocalizing output /cromwell_root/stdout -> gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/submissions/9bae57da-2431-4314-89ca-64714a8070e2/panoply_main/151a5dfa-f5b2-478a-bf0f-be053843e850/call-ssgsea_ome/stdout
2024/03/22 16:06:04 Delocalizing output /cromwell_root/stderr -> gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/submissions/9bae57da-2431-4314-89ca-64714a8070e2/panoply_main/151a5dfa-f5b2-478a-bf0f-be053843e850/call-ssgsea_ome/stderr
2024/03/22 16:06:07 Delocalizing output /cromwell_root/tutorial-proteome.tar.gz -> gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/submissions/9bae57da-2431-4314-89ca-64714a8070e2/panoply_main/151a5dfa-f5b2-478a-bf0f-be053843e850/call-ssgsea_ome/tutorial-proteome.tar.gz
Required file output '/cromwell_root/tutorial-proteome.tar.gz' does not exist.
</details>

<details>
<summary>
assoc.log
</summary>
2024/03/22 16:03:52 Starting container setup.
2024/03/22 16:03:54 Done container setup.
2024/03/22 16:03:54 Starting localization.
2024/03/22 16:04:03 Localization script execution started...
2024/03/22 16:04:03 Localizing input gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/submissions/9bae57da-2431-4314-89ca-64714a8070e2/panoply_main/151a5dfa-f5b2-478a-bf0f-be053843e850/call-panoply_association_workflow/assoc_workflow.panoply_association_workflow/a1f65b46-1697-4527-aaf0-f8e0a892776a/call-assoc/script -> /cromwell_root/script
2024/03/22 16:04:06 Localizing input gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/groups-subset.csv -> /cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/groups-subset.csv
2024/03/22 16:04:07 Localizing input gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/master-parameters_tutorial.yaml -> /cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/master-parameters_tutorial.yaml
2024/03/22 16:04:07 Localizing input gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/proteome-subset.gct -> /cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/proteome-subset.gct
Copying gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/master-parameters_tutorial.yaml to file:///cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/master-parameters_tutorial.yaml
Copying gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/proteome-subset.gct to file:///cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/proteome-subset.gct
  
.

Average throughput: 45.8MiB/s
2024/03/22 16:04:09 Localization script execution complete.
2024/03/22 16:04:13 Done localization.
2024/03/22 16:04:13 Running user action: docker run -v /mnt/local-disk:/cromwell_root --entrypoint=/bin/bash broadcptac/panoply_association@sha256:ae088ec96a1325101c5e05601c571a26682fa30d285cc60f44c5eeb9280b1056 /cromwell_root/script
NULL
NULL
Error in source("config.r") : config.r:300:1: unexpected '}'
299:   min.numratio <- 
300: }
     ^
Execution halted
2024/03/22 16:04:16 Starting delocalization.
2024/03/22 16:04:17 Delocalization script execution started...
2024/03/22 16:04:17 Delocalizing output /cromwell_root/memory_retry_rc -> gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/submissions/9bae57da-2431-4314-89ca-64714a8070e2/panoply_main/151a5dfa-f5b2-478a-bf0f-be053843e850/call-panoply_association_workflow/assoc_workflow.panoply_association_workflow/a1f65b46-1697-4527-aaf0-f8e0a892776a/call-assoc/memory_retry_rc
2024/03/22 16:04:19 Delocalizing output /cromwell_root/rc -> gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/submissions/9bae57da-2431-4314-89ca-64714a8070e2/panoply_main/151a5dfa-f5b2-478a-bf0f-be053843e850/call-panoply_association_workflow/assoc_workflow.panoply_association_workflow/a1f65b46-1697-4527-aaf0-f8e0a892776a/call-assoc/rc
2024/03/22 16:04:21 Delocalizing output /cromwell_root/stdout -> gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/submissions/9bae57da-2431-4314-89ca-64714a8070e2/panoply_main/151a5dfa-f5b2-478a-bf0f-be053843e850/call-panoply_association_workflow/assoc_workflow.panoply_association_workflow/a1f65b46-1697-4527-aaf0-f8e0a892776a/call-assoc/stdout
2024/03/22 16:04:22 Delocalizing output /cromwell_root/stderr -> gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/submissions/9bae57da-2431-4314-89ca-64714a8070e2/panoply_main/151a5dfa-f5b2-478a-bf0f-be053843e850/call-panoply_association_workflow/assoc_workflow.panoply_association_workflow/a1f65b46-1697-4527-aaf0-f8e0a892776a/call-assoc/stderr
2024/03/22 16:04:23 Delocalizing output /cromwell_root/panoply_association-output.tar -> gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/submissions/9bae57da-2431-4314-89ca-64714a8070e2/panoply_main/151a5dfa-f5b2-478a-bf0f-be053843e850/call-panoply_association_workflow/assoc_workflow.panoply_association_workflow/a1f65b46-1697-4527-aaf0-f8e0a892776a/call-assoc/panoply_association-output.tar
Required file output '/cromwell_root/panoply_association-output.tar' does not exist.
</details>

<details>
<summary>
panoply_ssgsea.log
</summary>
2024/03/22 16:44:55 Starting container setup.
2024/03/22 16:44:56 Done container setup.
2024/03/22 16:44:57 Starting localization.
2024/03/22 16:45:07 Localization script execution started...
2024/03/22 16:45:07 Localizing input gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/submissions/9bae57da-2431-4314-89ca-64714a8070e2/panoply_main/151a5dfa-f5b2-478a-bf0f-be053843e850/call-so_nmf/nmf_wdl.panoply_nmf_internal_workflow/00a87914-1254-4baa-a402-e59efcb803be/call-panoply_ssgsea/script -> /cromwell_root/script
2024/03/22 16:45:09 Localizing input gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/master-parameters_tutorial.yaml -> /cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/master-parameters_tutorial.yaml
2024/03/22 16:45:11 Localizing input gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/msigdb_v7.0_h.all.v7.0.symbols.gmt -> /cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/msigdb_v7.0_h.all.v7.0.symbols.gmt
Copying gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/msigdb_v7.0_h.all.v7.0.symbols.gmt to file:///cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/msigdb_v7.0_h.all.v7.0.symbols.gmt
  

2024/03/22 16:45:13 Localizing input gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/submissions/9bae57da-2431-4314-89ca-64714a8070e2/panoply_main/151a5dfa-f5b2-478a-bf0f-be053843e850/call-so_nmf/nmf_wdl.panoply_nmf_internal_workflow/00a87914-1254-4baa-a402-e59efcb803be/call-postprocess/glob-11ddd39ddf44cd39f6d839871aee5c17/tutorial-proteome_proteome_K3_W_rowNorm_combined_signed_n3x7198.gct -> /cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/submissions/9bae57da-2431-4314-89ca-64714a8070e2/panoply_main/151a5dfa-f5b2-478a-bf0f-be053843e850/call-so_nmf/nmf_wdl.panoply_nmf_internal_workflow/00a87914-1254-4baa-a402-e59efcb803be/call-postprocess/glob-11ddd39ddf44cd39f6d839871aee5c17/tutorial-proteome_proteome_K3_W_rowNorm_combined_signed_n3x7198.gct
2024/03/22 16:45:15 Localization script execution complete.
2024/03/22 16:45:19 Done localization.
2024/03/22 16:45:20 Running user action: docker run -v /mnt/local-disk:/cromwell_root --entrypoint=/bin/bash broadcptac/panoply_ssgsea@sha256:5bdb529bb513f986dd0786ade226e13a2e71b65b06abffd583803851861448f9 /cromwell_root/script


parsing command line parameters:
------------------------------------------------------------
--- gct_str /cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/submissions/9bae57da-2431-4314-89ca-64714a8070e2/panoply_main/151a5dfa-f5b2-478a-bf0f-be053843e850/call-so_nmf/nmf_wdl.panoply_nmf_internal_workflow/00a87914-1254-4baa-a402-e59efcb803be/call-postprocess/glob-11ddd39ddf44cd39f6d839871aee5c17/tutorial-proteome_proteome_K3_W_rowNorm_combined_signed_n3x7198.gct ; prefer yaml? FALSE 
--- level NA ; prefer yaml? TRUE 
--- id_type NA ; prefer yaml? TRUE 
--- id_type_out NA ; prefer yaml? TRUE 
--- acc_type_in NA ; prefer yaml? TRUE 
--- seqwin_column NA ; prefer yaml? TRUE 
--- gene_symbol_column NA ; prefer yaml? TRUE 
--- humanize_gene_names NA ; prefer yaml? TRUE 
--- sgt_column NA ; prefer yaml? TRUE 
--- localized NA ; prefer yaml? TRUE 
--- mode abs.max ; prefer yaml? FALSE 
--- residue NA ; prefer yaml? TRUE 
--- ptm NA ; prefer yaml? TRUE 
--- preprocess_gct NA ; prefer yaml? TRUE 
--- libdir /home/pgdac/src ; prefer yaml? FALSE 
--- yaml_file /cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/sample_sets/all/master-parameters_tutorial.yaml ; prefer yaml? FALSE 
--- help FALSE ; prefer yaml? FALSE 


Updating parameter file with command line parameters:
------------------------------------------------------------
mode : median -> abs.max 
------------------------------------------------------------ 

importing gct file:  /cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/submissions/9bae57da-2431-4314-89ca-64714a8070e2/panoply_main/151a5dfa-f5b2-478a-bf0f-be053843e850/call-so_nmf/nmf_wdl.panoply_nmf_internal_workflow/00a87914-1254-4baa-a402-e59efcb803be/call-postprocess/glob-11ddd39ddf44cd39f6d839871aee5c17/tutorial-proteome_proteome_K3_W_rowNorm_combined_signed_n3x7198.gct  ...
parsing as GCT v1.3
/cromwell_root/fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/submissions/9bae57da-2431-4314-89ca-64714a8070e2/panoply_main/151a5dfa-f5b2-478a-bf0f-be053843e850/call-so_nmf/nmf_wdl.panoply_nmf_internal_workflow/00a87914-1254-4baa-a402-e59efcb803be/call-postprocess/glob-11ddd39ddf44cd39f6d839871aee5c17/tutorial-proteome_proteome_K3_W_rowNorm_combined_signed_n3x7198.gct 7198 rows, 3 cols, 9 row descriptors, 0 col descriptors
Error in if (humanize.gene.names) genes <- toupper(genes) : 
  argument is not interpretable as logical
Calls: preprocessGCT
Execution halted
2024/03/22 16:45:30 Starting delocalization.
2024/03/22 16:45:31 Delocalization script execution started...
2024/03/22 16:45:31 Delocalizing output /cromwell_root/memory_retry_rc -> gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/submissions/9bae57da-2431-4314-89ca-64714a8070e2/panoply_main/151a5dfa-f5b2-478a-bf0f-be053843e850/call-so_nmf/nmf_wdl.panoply_nmf_internal_workflow/00a87914-1254-4baa-a402-e59efcb803be/call-panoply_ssgsea/memory_retry_rc
2024/03/22 16:45:34 Delocalizing output /cromwell_root/rc -> gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/submissions/9bae57da-2431-4314-89ca-64714a8070e2/panoply_main/151a5dfa-f5b2-478a-bf0f-be053843e850/call-so_nmf/nmf_wdl.panoply_nmf_internal_workflow/00a87914-1254-4baa-a402-e59efcb803be/call-panoply_ssgsea/rc
2024/03/22 16:45:36 Delocalizing output /cromwell_root/stdout -> gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/submissions/9bae57da-2431-4314-89ca-64714a8070e2/panoply_main/151a5dfa-f5b2-478a-bf0f-be053843e850/call-so_nmf/nmf_wdl.panoply_nmf_internal_workflow/00a87914-1254-4baa-a402-e59efcb803be/call-panoply_ssgsea/stdout
2024/03/22 16:45:38 Delocalizing output /cromwell_root/stderr -> gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/submissions/9bae57da-2431-4314-89ca-64714a8070e2/panoply_main/151a5dfa-f5b2-478a-bf0f-be053843e850/call-so_nmf/nmf_wdl.panoply_nmf_internal_workflow/00a87914-1254-4baa-a402-e59efcb803be/call-panoply_ssgsea/stderr
2024/03/22 16:45:39 Delocalizing output /cromwell_root/tutorial-proteome_proteome.tar.gz -> gs://fc-1fc25f57-17bc-442f-a03a-6359a27a1f08/submissions/9bae57da-2431-4314-89ca-64714a8070e2/panoply_main/151a5dfa-f5b2-478a-bf0f-be053843e850/call-so_nmf/nmf_wdl.panoply_nmf_internal_workflow/00a87914-1254-4baa-a402-e59efcb803be/call-panoply_ssgsea/tutorial-proteome_proteome.tar.gz
Required file output '/cromwell_root/tutorial-proteome_proteome.tar.gz' does not exist.
</details>

**Comment by wcorinne** [comment]
The majority of these errors look to be from parameter-mismatches. If this is occurring with the tutorial dataset (`tutorial-brca-input.zip`), it is likely that the `master-parameters_tutorial.yaml` in that zip file has not yet been updated to reflect v1_4. We are working on regenerating that tutorial zip-- but in the meantime, **excluding the `master-parameters_tutorial.yaml` from the zip file** (or, perhaps more simply, declaring `master-parameters_tutorial.yaml` as some other dummy file-category with `0` when running `panda_input()` in the notebook) will cause the notebook to generate a `master-parameters.yaml` file with the appropriate defaults for PANOPLY v1.4.

**Update:** The tutorial and `tutorial-brca-input.zip` have been updated to reflect PANOPLY v1.4 (2024-04-05)
